# Generated by Django 5.1.2 on 2024-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="code",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
